### PR TITLE
Dev testing and sorting

### PR DESCRIPTION
**Pull request by stevenwalton**
Sorted because why wasn't this done before?! Added bash, screen, tmux, useradd, usermod, and zsh. Modified git and vim. Needs serious work to become worthwhile for dev work.

### CODE REVIEW

**Comment by jasonwatt** [comment]
:+1:

**Comment by stevenwalton** [comment]
I need to also add that plugins **DO NOT** work at all in vim. Even something simple as tabular. I'm going to do some more testing with vim

**Comment by emmatyping** [comment]
There is a typo for zsh, but beyond that, it looks great. Thanks! :+1: Once you fix that, (and if you want to add more on vim), I'd be happy to merge!

**Comment by stevenwalton** [comment]
Fixed

**Comment by emmatyping** [comment]
Thanks again!

**Pull request merged**
