### PR TITLE
Reported sshuttle doesn't work in bash

### PR DESCRIPTION
**Pull request by Qoyyuum**

### CODE REVIEW

**Comment by emmatyping** [comment]
Hi, we try to keep things ordered alphabetically. If you could move the text up, that would be great. Thanks!

**Comment by Qoyyuum** [comment]
The original file wasn't in alphabetical order. Fixed it.

**Comment by emmatyping** [comment]
Did you mean to close this?

**Comment by Qoyyuum** [comment]
Sorry. First time contributing on Github and wasn't sure how this works.

**Comment by emmatyping** [comment]
No worries!

**Pull request merged**
