### PR TITLE
R on WSL

### PR DESCRIPTION
**Pull request by CrossD**
R seems to work well on WSL

### CODE REVIEW

**Comment by emmatyping** [comment]
Does "may be numerically different from other systems" hold special meaning in R? I am not sure I understand what you mean by that.

**Comment by aseering** [comment]
R is often used for statistical or modeling computations which are typically floating-point intensive.  Microsoft/BashOnWindows#830 tracks a bug in WSL that results in floating-point computations having reduced precision.  So the results of numerical computations may, indeed, be different (less accurate) as compared to other systems.

**Comment by emmatyping** [comment]
Thanks for the clarification @aseering and thanks for the contribution @CrossD

**Comment by CrossD** [comment]
Thanks @aseering for your clarification :) That is what I meant. Thanks for merging too @ethanhs !

**Pull request merged**
