### PR TITLE
Tested Tesseract-ocr

### PR DESCRIPTION
**Pull request by magnushammar**
No problems with command line usage

### CODE REVIEW

**Comment by emmatyping** [comment]
By no problems with usage, I hope you mean that the results came out as expected from the OCR engine?

**Comment by magnushammar** [comment]
Yes. I have tested all different strategies on Tiff image format. I have also tested it with tesseract-ocr-swe pretrained data. Everything work as expected.

**Comment by emmatyping** [comment]
Thanks so much!

**Comment by magnushammar** [comment]
Thanks back at you, for setting this repo up!

**Pull request merged**
