### PR TITLE
Add apt-fast, aria2c, c-ares

### PR DESCRIPTION
**Pull request by Efreak**
I'm not 100% sure that c-ares is the issue. Perhaps @bagder or [one of the other top contributors](https://github.com/c-ares/c-ares/graphs/contributors) to that project knows of a simple program to test ares with?

### CODE REVIEW

**Comment by emmatyping** [comment]
Thanks for the contribution. Feel free to file another pr if you have updates from the maintainers you mentioned.

**Comment by Efreak** [comment]
c-ares works fine when compiled from source (or at least, the ahost, adig commands work). I'm currently trying to figure out how to get c-ares packaged in an environment that doesn't support chroot or fakeroot (the dh_testroot doesn't seem to like fakechroot). Once I've got that figured out, I'll provide a package myself, and a short script to update it.

**Comment by bagder** [comment]
I agree. The ahost and adig programs are probably the easiest test programs to verify c-ares in a real system.

**Comment by Efreak** [comment]
This is not an issue with c-ares, though I haven't yet verified whether or not c-ares from ubuntu's repos works (it doesn't provide the test utilities). However, having built and installed c-ares (`libc-ares2` and `libc-ares-dev` packages) and then built and installed aria2 from source, aria2c still does not work. The self-built c-ares, however, _does_ work; the test utilities `adig` and `ahost` work fine:

```
root@Win10-vm-2:/home/Efreak/sources# c-ares-1.10.0/ahost google.com
google.com                              216.58.217.206
root@Win10-vm-2:/home/Efreak/sources# aria2-1.18.1/src/aria2c http://google.com

10/10 18:20:03 [ERROR] CUID#6 - Download aborted. URI=http://google.com
Exception: [AbstractCommand.cc:312] errorCode=19 URI=http://google.com
  -> [AbstractCommand.cc:739] errorCode=19 CUID#6 - Name resolution for google.com failed:No address returned
```

Edit: @bagder: I noticed that the configure script for c-ares takes a _long_ time on WSL, specifically when checking the parameters for RECV, RECVFROM, and SEND. If that's not normal, it might be something to look at. 

I'm going to go ahead and report this as a bug to [aria2](https://github.com/aria2/aria2)

**Pull request merged**
