### PR TITLE
Create website

### PR DESCRIPTION
**Pull request by Efreak**
I've created a website based on the slate jekyll theme, it looks like it's working fine to me. It's mostly the same, though there's a few slight changes (wording of table headers, escape pipes + remove header at the top, etc)

You can see it [here](https://efreak.github.io/WSL-Programs/).

### CODE REVIEW

**Comment by emmatyping** [comment]
Um, wow this is amazing! I don't know ruby/jekyll, so I have a few questions:
a) this will stay up to date if the readme is updated, right?
b) how easy is it to change the style? (Not that I want to now, I'm curious about if I just need to change a css file or something)

**Comment by Efreak** [comment]
You don't actually need to know ruby to use this.

A. It works off whatever branch is configured as the website; either use a gh-pages branch, or change the branch under the Github Pages heading in [repository settings](https://github.com/ethanhs/WSL-Programs/settings)
  - you can choose a different theme there if you want, but I've customized the Slate theme somewhat for removing download links, contributor listing, etc
  - Whenever you update the site, github will regenerate the website based on the theme; if there's a problem with it, you'll get an email (I've only ever had issues when I added jekyll/ruby features that weren't supported by github)
    - Sometimes there's a several-minute delay on changes being updated; if you want instant previews, [test locally](https://help.github.com/articles/setting-up-your-github-pages-site-locally-with-jekyll/)

B. The stylesheets are [SCSS](http://sass-lang.com/) files; [_sass/jekyll-theme-slate.scss](https://github.com/Efreak/WSL-Programs/blob/gh-pages/_sass/jekyll-theme-slate.scss), with some overrides in [assets/css](https://github.com/Efreak/WSL-Programs/blob/gh-pages/assets/css/style.scss). The html template is at [_layouts/default.html](https://github.com/Efreak/WSL-Programs/blob/gh-pages/_layouts/default.html). Variables referenced in the layout are defined in [_config.yml](https://github.com/Efreak/WSL-Programs/blob/gh-pages/_config.yml). SASS is [fairly simple to understand](https://scotch.io/tutorials/getting-started-with-sass), but you can also just use plain css.

Any other questions about how GitHub pages works with Jekyll can *probably* be answered by reading [Customizing GitHub Pages](https://help.github.com/categories/customizing-github-pages/)--more specifically, [Using Jekyll as a static site generator with GitHub Pages](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/)

**Comment by emmatyping** [comment]
Thanks so much!

**Comment by Efreak** [comment]
If you pull the updates from my branch again, it'll add sorting to the table thru [sorttable.js](https://github.com/stuartlangridge/sorttable). It should be simple if you rebase, but if you need to go thru github, let me know and I'll create a pull request for it.

Preview [here](https://efreak.github.io/WSL-Programs/)--just click one of the table headers to sort.

Also, I recommend removing the website column, and either making the program name (or apt name where website is ppa like haxe) clickable, or putting it in the notes column.

**Pull request merged**
